# Generated by Django 6.0.5 on 2026-05-07 19:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_limit', models.PositiveIntegerField(default=12)),
                ('author_paper_limit', models.PositiveIntegerField(default=3)),
                ('title_words_for_filename', models.PositiveIntegerField(default=5)),
                ('incoming_folder', models.CharField(default='data/incoming', max_length=500)),
                ('active_final_folder', models.CharField(default='data/active_final', max_length=500)),
                ('old_versions_folder', models.CharField(default='data/old_versions', max_length=500)),
                ('reports_folder', models.CharField(default='data/reports', max_length=500)),
                ('extraction_results_folder', models.CharField(default='data/extraction_results', max_length=500)),
                ('plagiarism_reports_folder', models.CharField(default='data/plagiarism_reports', max_length=500)),
            ],
            options={
                'verbose_name': 'Application setting',
                'verbose_name_plural': 'Application settings',
            },
        ),
        migrations.CreateModel(
            name='FinalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_submission_id', models.CharField(max_length=100, unique=True)),
                ('paper_id_filled', models.CharField(blank=True, db_index=True, max_length=150)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='final_submissions/')),
                ('current_file_path', models.TextField(blank=True)),
                ('extracted_title', models.CharField(blank=True, max_length=500)),
                ('extracted_authors', models.TextField(blank=True)),
                ('title_author_source', models.CharField(choices=[('unknown', 'Unknown'), ('manual', 'Manual'), ('external_import', 'External import')], default='unknown', max_length=30)),
                ('title_author_imported_at', models.DateTimeField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pdf_hash', models.CharField(blank=True, max_length=64)),
                ('active_version', models.BooleanField(db_index=True, default=True)),
                ('plagiarism_status', models.CharField(blank=True, choices=[('', 'Missing'), ('pending', 'Pending'), ('clear', 'Clear'), ('review', 'Needs review'), ('flagged', 'Flagged')], default='', max_length=30)),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('plagiarism_report_path', models.TextField(blank=True)),
                ('plagiarism_imported_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=30)),
                ('processing_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['paper_id_filled', '-upload_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitialPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_submission_id', models.CharField(max_length=100, unique=True)),
                ('track', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.TextField(blank=True)),
                ('corresponding_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['paper_id'],
            },
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(db_index=True, max_length=150)),
                ('author_name', models.CharField(max_length=255)),
                ('normalized_author_name', models.CharField(db_index=True, max_length=255)),
                ('author_order', models.PositiveIntegerField(default=1)),
                ('final_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_authors', to='submissions.finalsubmission')),
            ],
            options={
                'ordering': ['normalized_author_name', 'paper_id', 'author_order'],
                'unique_together': {('final_submission', 'normalized_author_name', 'author_order')},
            },
        ),
    ]
