# Generated by Django 6.0.5 on 2026-05-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='duplicate_submission',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='final_submission_authors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='final_submission_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='mapping_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='mapping_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='start2_paper_id_raw',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='initialpaper',
            name='track',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
