# Generated by Django 6.0.5 on 2026-05-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_finalsubmission_duplicate_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialpaper',
            name='initial_submission_id',
        ),
        migrations.RenameField(
            model_name='initialpaper',
            old_name='track',
            new_name='acceptance_status',
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='paper_id_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='title_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='verification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('title_mismatch', 'Title mismatch'), ('invalid_paper_id', 'Invalid Paper ID')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
