# Generated by Django 6.0.5 on 2026-05-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_initialpaper_initial_submission_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='source_current_file_path',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='source_submissions/'),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='source_original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
