# Generated by Django 6.0.5 on 2026-05-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_finalsubmission_source_current_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='auto_verify_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
