# Generated by Django 6.0.5 on 2026-05-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_finalsubmission_auto_verify_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='page_minimum',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='thumbnail_folder',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='thumbnail_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='thumbnail_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
