# Generated by Django 6.0.5 on 2026-05-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_appsetting_page_minimum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='title_author_script_path',
            field=models.CharField(default='/Users/kevin/Codes/UTDConferenceTools/PDF Title/ExportTitleAuthor.py', max_length=700),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='title_author_extraction_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='title_author_extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('error', 'Error')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='title_author_verification_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='title_author_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='title_author_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalsubmission',
            name='title_author_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('manual', 'Manual'), ('external_import', 'External import'), ('external_script', 'External script')], default='unknown', max_length=30),
        ),
    ]
