# Generated by Django 6.0.5 on 2026-05-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_appsetting_title_author_script_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='extracted_title_auto_verify_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='extracted_title_match_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='extracted_title_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='extracted_title_match_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('title_mismatch', 'Title mismatch'), ('missing', 'Missing title')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='extracted_title_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='extracted_title_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='format_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='format_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_edit', 'Needs edit'), ('edited', 'Edited'), ('verified', 'Verified')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='formatted_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='formatted_pdfs/'),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='formatted_pdf_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='formatted_source_file',
            field=models.FileField(blank=True, null=True, upload_to='formatted_sources/'),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='formatted_source_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
