# Generated by Django 6.0.5 on 2026-05-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_finalsubmission_extracted_title_auto_verify_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='max_authors_per_paper',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
