# Generated by Django 6.0.5 on 2026-05-08 00:15

from django.db import migrations, models


def migrate_format_status_forward(apps, schema_editor):
    FinalSubmission = apps.get_model("submissions", "FinalSubmission")
    FinalSubmission.objects.filter(format_status="verified").update(format_status="review_ok")
    FinalSubmission.objects.filter(format_status="edited").update(format_status="pending")


def migrate_format_status_backward(apps, schema_editor):
    FinalSubmission = apps.get_model("submissions", "FinalSubmission")
    FinalSubmission.objects.filter(format_status="review_ok").update(format_status="verified")


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_appsetting_max_authors_per_paper'),
    ]

    operations = [
        migrations.RunPython(migrate_format_status_forward, migrate_format_status_backward),
        migrations.AlterField(
            model_name='finalsubmission',
            name='format_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_edit', 'Needs edit'), ('review_ok', 'Review OK')], db_index=True, default='pending', max_length=30),
        ),
    ]
