# Generated by Django 6.0.5 on 2026-05-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_alter_finalsubmission_format_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='plagiarism_percent_threshold',
            field=models.DecimalField(decimal_places=2, default=35, max_digits=5),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='single_similarity_threshold',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='single_similarity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
