# Generated by Django 6.0.5 on 2026-05-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_appsetting_plagiarism_percent_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='active_version_rule',
            field=models.CharField(choices=[('final_id', 'Largest Final ID'), ('upload_date', 'Latest upload date')], default='final_id', max_length=30),
        ),
    ]
