# Generated by Django 6.0.5 on 2026-05-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0012_appsetting_active_version_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='time_zone',
            field=models.CharField(choices=[('America/Chicago', 'Dallas / Central Time'), ('America/New_York', 'Eastern Time'), ('America/Denver', 'Mountain Time'), ('America/Los_Angeles', 'Pacific Time'), ('UTC', 'UTC')], default='America/Chicago', max_length=80),
        ),
    ]
