# Generated by Django 6.0.5 on 2026-05-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_appsetting_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='excluded_from_publication',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='publication_excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='publication_exclusion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='publication_exclusion_reason',
            field=models.CharField(blank=True, choices=[('', 'Not excluded'), ('unpaid', 'Unpaid'), ('withdrawn', 'Withdrawn'), ('not_in_master', 'Not in Master List'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
