# Generated by Django 6.0.5 on 2026-05-08 18:46

from django.db import migrations, models


def copy_existing_title_author_review_state(apps, schema_editor):
    FinalSubmission = apps.get_model("submissions", "FinalSubmission")
    FinalSubmission.objects.filter(title_author_verified=True).update(
        title_author_review_status="review_ok"
    )
    FinalSubmission.objects.filter(title_author_verified=False).update(
        title_author_review_status="pending",
        title_author_verified_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_finalsubmission_excluded_from_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='title_author_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('red_flag', 'Red Flag'), ('review_ok', 'Review OK')], db_index=True, default='pending', max_length=30),
        ),
        migrations.RunPython(
            copy_existing_title_author_review_state,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
