# Generated by Django 6.0.5 on 2026-05-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_finalsubmission_title_author_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='duplicate_author_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='duplicate_author_review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review_ok', 'Review OK')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='duplicate_author_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
