# Generated by Django 6.0.5 on 2026-05-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0016_finalsubmission_duplicate_author_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='plagiarism_report_stale',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
