# Generated by Django 6.0.5 on 2026-05-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0017_finalsubmission_plagiarism_report_stale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsetting',
            name='title_author_script_path',
        ),
    ]
