# Generated by Django 6.0.5 on 2026-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0018_remove_appsetting_title_author_script_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorLimitWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_author_name', models.CharField(max_length=255, unique=True)),
                ('display_author_name', models.CharField(blank=True, max_length=255)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('reason', models.TextField(blank=True)),
                ('approved_publication_paper_count', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['normalized_author_name'],
            },
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='author_number_exception_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='author_number_exception_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='author_number_exception_author_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='author_number_exception_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='page_limit_exception_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='page_limit_exception_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='page_limit_exception_page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='page_limit_exception_reason',
            field=models.TextField(blank=True),
        ),
    ]
