# Generated by Django 6.0.5 on 2026-05-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0019_authorlimitwaiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='conference_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
