# Generated by Django 6.0.5 on 2026-05-09 02:15

import django.db.models.deletion
from django.db import migrations, models


def populate_final_submission_states(apps, schema_editor):
    FinalSubmission = apps.get_model('submissions', 'FinalSubmission')
    IdentityState = apps.get_model('submissions', 'FinalSubmissionIdentityState')
    FileState = apps.get_model('submissions', 'FinalSubmissionFileState')
    ReviewState = apps.get_model('submissions', 'FinalSubmissionReviewState')
    PublicationState = apps.get_model('submissions', 'FinalSubmissionPublicationState')
    PlagiarismState = apps.get_model('submissions', 'FinalSubmissionPlagiarismState')
    for submission in FinalSubmission.objects.all().iterator():
        IdentityState.objects.create(
            final_submission=submission,
            submission_identifier=submission.final_submission_id,
            start2_paper_id_raw=submission.start2_paper_id_raw,
            paper_id_filled=submission.paper_id_filled,
            final_submission_title=submission.final_submission_title,
            final_submission_authors=submission.final_submission_authors,
            upload_date=submission.upload_date,
            active_version=submission.active_version,
            duplicate_submission=submission.duplicate_submission,
            mapping_source=submission.mapping_source,
            mapping_order=submission.mapping_order,
        )
        FileState.objects.create(
            final_submission=submission,
            original_file_name=submission.original_file_name,
            pdf_file_name=submission.pdf_file.name if submission.pdf_file else '',
            source_original_file_name=submission.source_original_file_name,
            source_file_name=submission.source_file.name if submission.source_file else '',
            current_file_path=submission.current_file_path,
            source_current_file_path=submission.source_current_file_path,
            formatted_pdf_file_name=(
                submission.formatted_pdf_file.name if submission.formatted_pdf_file else ''
            ),
            formatted_source_file_name=(
                submission.formatted_source_file.name if submission.formatted_source_file else ''
            ),
            formatted_pdf_uploaded_at=submission.formatted_pdf_uploaded_at,
            formatted_source_uploaded_at=submission.formatted_source_uploaded_at,
            page_count=submission.page_count,
            pdf_hash=submission.pdf_hash,
            thumbnail_folder=submission.thumbnail_folder,
            thumbnail_status=submission.thumbnail_status,
            thumbnail_message=submission.thumbnail_message,
            processing_status=submission.processing_status,
            processing_message=submission.processing_message,
        )
        ReviewState.objects.create(
            final_submission=submission,
            paper_id_verified=submission.paper_id_verified,
            auto_verify_blocked=submission.auto_verify_blocked,
            verification_status=submission.verification_status,
            title_match_score=submission.title_match_score,
            verification_message=submission.verification_message,
            verified_at=submission.verified_at,
            extracted_title=submission.extracted_title,
            extracted_authors=submission.extracted_authors,
            title_author_source=submission.title_author_source,
            title_author_imported_at=submission.title_author_imported_at,
            title_author_extraction_status=submission.title_author_extraction_status,
            title_author_extraction_message=submission.title_author_extraction_message,
            title_author_verification_image=submission.title_author_verification_image,
            title_author_verified=submission.title_author_verified,
            title_author_verified_at=submission.title_author_verified_at,
            title_author_review_status=submission.title_author_review_status,
            duplicate_author_review_status=submission.duplicate_author_review_status,
            duplicate_author_review_notes=submission.duplicate_author_review_notes,
            duplicate_author_reviewed_at=submission.duplicate_author_reviewed_at,
            extracted_title_match_status=submission.extracted_title_match_status,
            extracted_title_match_score=submission.extracted_title_match_score,
            extracted_title_match_message=submission.extracted_title_match_message,
            extracted_title_verified=submission.extracted_title_verified,
            extracted_title_auto_verify_blocked=submission.extracted_title_auto_verify_blocked,
            extracted_title_verified_at=submission.extracted_title_verified_at,
            format_status=submission.format_status,
            format_notes=submission.format_notes,
        )
        PublicationState.objects.create(
            final_submission=submission,
            excluded_from_publication=submission.excluded_from_publication,
            publication_exclusion_reason=submission.publication_exclusion_reason,
            publication_exclusion_notes=submission.publication_exclusion_notes,
            publication_excluded_at=submission.publication_excluded_at,
            page_limit_exception_approved=submission.page_limit_exception_approved,
            page_limit_exception_reason=submission.page_limit_exception_reason,
            page_limit_exception_page_count=submission.page_limit_exception_page_count,
            page_limit_exception_approved_at=submission.page_limit_exception_approved_at,
            author_number_exception_approved=submission.author_number_exception_approved,
            author_number_exception_reason=submission.author_number_exception_reason,
            author_number_exception_author_count=(
                submission.author_number_exception_author_count
            ),
            author_number_exception_approved_at=(
                submission.author_number_exception_approved_at
            ),
        )
        PlagiarismState.objects.create(
            final_submission=submission,
            plagiarism_status=submission.plagiarism_status,
            similarity_score=submission.similarity_score,
            single_similarity_score=submission.single_similarity_score,
            plagiarism_report_path=submission.plagiarism_report_path,
            plagiarism_report_stale=submission.plagiarism_report_stale,
            plagiarism_imported_at=submission.plagiarism_imported_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0020_appsetting_conference_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalSubmissionFileState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(blank=True, max_length=255)),
                ('pdf_file_name', models.TextField(blank=True)),
                ('source_original_file_name', models.CharField(blank=True, max_length=255)),
                ('source_file_name', models.TextField(blank=True)),
                ('current_file_path', models.TextField(blank=True)),
                ('source_current_file_path', models.TextField(blank=True)),
                ('formatted_pdf_file_name', models.TextField(blank=True)),
                ('formatted_source_file_name', models.TextField(blank=True)),
                ('formatted_pdf_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('formatted_source_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('pdf_hash', models.CharField(blank=True, max_length=64)),
                ('thumbnail_folder', models.TextField(blank=True)),
                ('thumbnail_status', models.CharField(blank=True, max_length=30)),
                ('thumbnail_message', models.TextField(blank=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=30)),
                ('processing_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_state', to='submissions.finalsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSubmissionIdentityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_identifier', models.CharField(db_index=True, max_length=100)),
                ('start2_paper_id_raw', models.CharField(blank=True, max_length=150)),
                ('paper_id_filled', models.CharField(blank=True, db_index=True, max_length=150)),
                ('final_submission_title', models.CharField(blank=True, max_length=500)),
                ('final_submission_authors', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField()),
                ('active_version', models.BooleanField(db_index=True, default=True)),
                ('duplicate_submission', models.BooleanField(db_index=True, default=False)),
                ('mapping_source', models.CharField(blank=True, max_length=100)),
                ('mapping_order', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_state', to='submissions.finalsubmission')),
            ],
            options={
                'ordering': ['paper_id_filled', '-upload_date', 'submission_identifier'],
            },
        ),
        migrations.CreateModel(
            name='FinalSubmissionPlagiarismState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plagiarism_status', models.CharField(blank=True, choices=[('', 'Missing'), ('pending', 'Pending'), ('clear', 'Clear'), ('review', 'Needs review'), ('flagged', 'Flagged')], default='', max_length=30)),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('single_similarity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('plagiarism_report_path', models.TextField(blank=True)),
                ('plagiarism_report_stale', models.BooleanField(db_index=True, default=False)),
                ('plagiarism_imported_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_state', to='submissions.finalsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSubmissionPublicationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_from_publication', models.BooleanField(db_index=True, default=False)),
                ('publication_exclusion_reason', models.CharField(blank=True, choices=[('', 'Not excluded'), ('unpaid', 'Unpaid'), ('withdrawn', 'Withdrawn'), ('not_in_master', 'Not in Master List'), ('other', 'Other')], default='', max_length=30)),
                ('publication_exclusion_notes', models.TextField(blank=True)),
                ('publication_excluded_at', models.DateTimeField(blank=True, null=True)),
                ('page_limit_exception_approved', models.BooleanField(db_index=True, default=False)),
                ('page_limit_exception_reason', models.TextField(blank=True)),
                ('page_limit_exception_page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('page_limit_exception_approved_at', models.DateTimeField(blank=True, null=True)),
                ('author_number_exception_approved', models.BooleanField(db_index=True, default=False)),
                ('author_number_exception_reason', models.TextField(blank=True)),
                ('author_number_exception_author_count', models.PositiveIntegerField(blank=True, null=True)),
                ('author_number_exception_approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication_state', to='submissions.finalsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='FinalSubmissionReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id_verified', models.BooleanField(db_index=True, default=False)),
                ('auto_verify_blocked', models.BooleanField(db_index=True, default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('title_mismatch', 'Title mismatch'), ('invalid_paper_id', 'Invalid Paper ID')], default='pending', max_length=30)),
                ('title_match_score', models.FloatField(blank=True, null=True)),
                ('verification_message', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_title', models.CharField(blank=True, max_length=500)),
                ('extracted_authors', models.TextField(blank=True)),
                ('title_author_source', models.CharField(choices=[('unknown', 'Unknown'), ('manual', 'Manual'), ('external_import', 'External import'), ('external_script', 'External script')], default='unknown', max_length=30)),
                ('title_author_imported_at', models.DateTimeField(blank=True, null=True)),
                ('title_author_extraction_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('error', 'Error')], default='pending', max_length=30)),
                ('title_author_extraction_message', models.TextField(blank=True)),
                ('title_author_verification_image', models.TextField(blank=True)),
                ('title_author_verified', models.BooleanField(db_index=True, default=False)),
                ('title_author_verified_at', models.DateTimeField(blank=True, null=True)),
                ('title_author_review_status', models.CharField(choices=[('pending', 'Pending'), ('red_flag', 'Red Flag'), ('review_ok', 'Review OK')], db_index=True, default='pending', max_length=30)),
                ('duplicate_author_review_status', models.CharField(choices=[('pending', 'Pending'), ('review_ok', 'Review OK')], db_index=True, default='pending', max_length=30)),
                ('duplicate_author_review_notes', models.TextField(blank=True)),
                ('duplicate_author_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_title_match_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('title_mismatch', 'Title mismatch'), ('missing', 'Missing title')], default='pending', max_length=30)),
                ('extracted_title_match_score', models.FloatField(blank=True, null=True)),
                ('extracted_title_match_message', models.TextField(blank=True)),
                ('extracted_title_verified', models.BooleanField(db_index=True, default=False)),
                ('extracted_title_auto_verify_blocked', models.BooleanField(db_index=True, default=False)),
                ('extracted_title_verified_at', models.DateTimeField(blank=True, null=True)),
                ('format_status', models.CharField(choices=[('pending', 'Pending'), ('needs_edit', 'Needs edit'), ('review_ok', 'Review OK')], db_index=True, default='pending', max_length=30)),
                ('format_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_state', to='submissions.finalsubmission')),
            ],
        ),
        migrations.RunPython(populate_final_submission_states, migrations.RunPython.noop),
    ]
