# Generated by Django 6.0.5 on 2026-05-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0021_finalsubmissionfilestate_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finalsubmission',
            index=models.Index(fields=['active_version', 'excluded_from_publication', 'paper_id_filled'], name='sub_final_active_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='finalsubmission',
            index=models.Index(fields=['active_version', 'title_author_review_status', 'extracted_title_verified'], name='sub_final_title_review_idx'),
        ),
        migrations.AddIndex(
            model_name='finalsubmission',
            index=models.Index(fields=['active_version', 'format_status'], name='sub_final_format_idx'),
        ),
    ]
