# Generated by Django 6.0.5 on 2026-05-09 04:39

from django.db import migrations, models


def backfill_builtin_title_author_source(apps, schema_editor):
    FinalSubmission = apps.get_model("submissions", "FinalSubmission")
    FinalSubmission.objects.filter(
        title_author_source="unknown",
        title_author_extraction_status="extracted",
    ).exclude(
        extracted_title="",
        extracted_authors="",
    ).update(title_author_source="built_in_extractor")

    FinalSubmissionReviewState = apps.get_model("submissions", "FinalSubmissionReviewState")
    FinalSubmissionReviewState.objects.filter(
        title_author_source="unknown",
        title_author_extraction_status="extracted",
    ).exclude(
        extracted_title="",
        extracted_authors="",
    ).update(title_author_source="built_in_extractor")


def reverse_builtin_title_author_source(apps, schema_editor):
    FinalSubmission = apps.get_model("submissions", "FinalSubmission")
    FinalSubmission.objects.filter(title_author_source="built_in_extractor").update(
        title_author_source="unknown"
    )

    FinalSubmissionReviewState = apps.get_model("submissions", "FinalSubmissionReviewState")
    FinalSubmissionReviewState.objects.filter(title_author_source="built_in_extractor").update(
        title_author_source="unknown"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0022_finalsubmission_sub_final_active_pub_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalsubmission',
            name='title_author_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('built_in_extractor', 'Built-in extractor'), ('manual', 'Manual'), ('external_import', 'External import'), ('external_script', 'External script')], default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='finalsubmissionreviewstate',
            name='title_author_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('built_in_extractor', 'Built-in extractor'), ('manual', 'Manual'), ('external_import', 'External import'), ('external_script', 'External script')], default='unknown', max_length=30),
        ),
        migrations.RunPython(
            backfill_builtin_title_author_source,
            reverse_builtin_title_author_source,
        ),
    ]
