# Generated by Django 6.0.5 on 2026-05-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0023_title_author_builtin_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='discard_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='discarded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='editor_upload_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='editor_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='submission_origin',
            field=models.CharField(choices=[('start2', 'Start2'), ('editor_upload', 'Editor Upload')], db_index=True, default='start2', max_length=30),
        ),
        migrations.AddField(
            model_name='finalsubmissionidentitystate',
            name='editor_upload_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionidentitystate',
            name='editor_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionidentitystate',
            name='submission_origin',
            field=models.CharField(choices=[('start2', 'Start2'), ('editor_upload', 'Editor Upload')], db_index=True, default='start2', max_length=30),
        ),
        migrations.AddField(
            model_name='finalsubmissionpublicationstate',
            name='discard_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionpublicationstate',
            name='discarded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmissionpublicationstate',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
