# Generated by Django 6.0.5 on 2026-05-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0024_finalsubmission_discard_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialpaper',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
