# Generated by Django 6.0.5 on 2026-05-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0025_initialpaper_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='publication_pdf_debug_folder',
            field=models.CharField(default='data/publication_pdf_debug', max_length=500),
        ),
    ]
