# Generated by Django 6.0.5 on 2026-06-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0026_appsetting_publication_pdf_debug_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='grobid_api_url',
            field=models.CharField(default='http://localhost:8070', max_length=500),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='grobid_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='grobid_timeout_seconds',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='finalsubmission',
            name='title_author_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('built_in_extractor', 'Built-in extractor'), ('grobid', 'GROBID'), ('manual', 'Manual'), ('external_import', 'External import'), ('external_script', 'External script')], default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='finalsubmissionreviewstate',
            name='title_author_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('built_in_extractor', 'Built-in extractor'), ('grobid', 'GROBID'), ('manual', 'Manual'), ('external_import', 'External import'), ('external_script', 'External script')], default='unknown', max_length=30),
        ),
    ]
