# Generated by Django 6.0.5 on 2026-06-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0027_appsetting_grobid_api_url_appsetting_grobid_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='title_author_manual_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='title_author_manual_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionreviewstate',
            name='title_author_manual_override_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionreviewstate',
            name='title_author_manual_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finalsubmission',
            name='title_author_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('built_in_extractor', 'Built-in extractor'), ('grobid', 'GROBID'), ('manual_override', 'Manual override'), ('manual', 'Manual'), ('external_import', 'External import'), ('external_script', 'External script')], default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='finalsubmissionreviewstate',
            name='title_author_source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('built_in_extractor', 'Built-in extractor'), ('grobid', 'GROBID'), ('manual_override', 'Manual override'), ('manual', 'Manual'), ('external_import', 'External import'), ('external_script', 'External script')], default='unknown', max_length=30),
        ),
    ]
