# Generated by Django 6.0.5 on 2026-06-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0028_finalsubmission_title_author_manual_override_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmission',
            name='plagiarism_percent_exception_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='plagiarism_percent_exception_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='plagiarism_percent_exception_approved_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='plagiarism_percent_exception_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='single_percent_exception_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='single_percent_exception_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='single_percent_exception_approved_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmission',
            name='single_percent_exception_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionplagiarismstate',
            name='plagiarism_percent_exception_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmissionplagiarismstate',
            name='plagiarism_percent_exception_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionplagiarismstate',
            name='plagiarism_percent_exception_approved_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionplagiarismstate',
            name='plagiarism_percent_exception_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionplagiarismstate',
            name='single_percent_exception_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='finalsubmissionplagiarismstate',
            name='single_percent_exception_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionplagiarismstate',
            name='single_percent_exception_approved_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='finalsubmissionplagiarismstate',
            name='single_percent_exception_reason',
            field=models.TextField(blank=True),
        ),
    ]
