# Generated by Django 6.0.5 on 2026-07-27 22:12

from django.db import migrations, models


def migrate_master_publication_decisions(apps, schema_editor):
    InitialPaper = apps.get_model("submissions", "InitialPaper")
    FinalSubmission = apps.get_model("submissions", "FinalSubmission")

    for paper in InitialPaper.objects.all().iterator():
        decisions = list(
            FinalSubmission.objects.filter(
                paper_id_filled=paper.paper_id,
            ).values_list("excluded_from_publication", flat=True)
        )
        if not decisions or not any(decisions):
            continue
        if not all(decisions):
            paper.publication_decision_status = "decision_required"
            paper.save(update_fields=["publication_decision_status"])
            continue

        source = (
            FinalSubmission.objects.filter(
                paper_id_filled=paper.paper_id,
                excluded_from_publication=True,
            )
            .order_by("-active_version", "-publication_excluded_at", "-pk")
            .first()
        )
        paper.publication_decision_status = "not_publishing"
        paper.publication_exclusion_reason = (
            source.publication_exclusion_reason or "other"
        )
        paper.publication_exclusion_notes = source.publication_exclusion_notes
        paper.publication_excluded_at = (
            source.publication_excluded_at or source.updated_at
        )
        paper.save(
            update_fields=[
                "publication_decision_status",
                "publication_exclusion_reason",
                "publication_exclusion_notes",
                "publication_excluded_at",
            ]
        )


def clear_master_publication_decisions(apps, schema_editor):
    InitialPaper = apps.get_model("submissions", "InitialPaper")
    InitialPaper.objects.update(
        publication_decision_status="publishing",
        publication_exclusion_reason="",
        publication_exclusion_notes="",
        publication_excluded_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0031_initialpaper_normalized_paper_id_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialpaper',
            name='publication_decision_status',
            field=models.CharField(choices=[('publishing', 'Publishing'), ('not_publishing', 'Not Publishing'), ('decision_required', 'Decision required')], db_index=True, default='publishing', max_length=30),
        ),
        migrations.AddField(
            model_name='initialpaper',
            name='publication_excluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='initialpaper',
            name='publication_exclusion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='initialpaper',
            name='publication_exclusion_reason',
            field=models.CharField(blank=True, choices=[('', 'Not excluded'), ('unpaid', 'Unpaid'), ('withdrawn', 'Withdrawn'), ('not_in_master', 'Not in Master List'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.RunPython(
            migrate_master_publication_decisions,
            clear_master_publication_decisions,
        ),
        migrations.AddConstraint(
            model_name='initialpaper',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_decision_status', 'publishing'), ('publication_excluded_at__isnull', True), ('publication_exclusion_notes', ''), ('publication_exclusion_reason', '')), models.Q(('publication_decision_status', 'not_publishing'), ('publication_excluded_at__isnull', False), models.Q(('publication_exclusion_reason', ''), _negated=True)), ('publication_decision_status', 'decision_required'), _connector='OR'), name='initialpaper_publication_decision_valid'),
        ),
    ]
