# Generated by Django 6.0.5 on 2026-07-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0032_initialpaper_publication_decision_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalsubmission',
            name='mapping_order',
        ),
        migrations.RemoveField(
            model_name='finalsubmission',
            name='mapping_source',
        ),
        migrations.RemoveField(
            model_name='finalsubmissionidentitystate',
            name='mapping_order',
        ),
        migrations.RemoveField(
            model_name='finalsubmissionidentitystate',
            name='mapping_source',
        ),
    ]
